source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '10.0'
use_frameworks!

target 'Joke8' do
    pod 'SnapKit', '~> 3.2.0'
    pod ‘MBProgressHUD’, '~> 1.0.0’
    pod 'Alamofire', '~> 4.4'
    pod ‘RealmSwift’, '~> 2.9.1’
end